using System.Numerics;
using System.Runtime.InteropServices;

namespace Rekall.Age.Rendering;

public static class RekallAgeVulkanSceneUniformUploadBuilder
{
    public static RekallAgeVulkanSceneGpuFrameUniform BuildFrameUniform(
        RekallAgeVulkanSceneFrameUniform frame,
        RekallAgeVulkanShadowPlan? shadowPlan = null)
    {
        var cascades = shadowPlan?.Cascades ?? [];
        var split0 = cascades.Count > 0 ? cascades[0].SplitFar : 0;
        var split1 = cascades.Count > 1 ? cascades[1].SplitFar : split0;
        var split2 = cascades.Count > 2 ? cascades[2].SplitFar : split1;
        var split3 = cascades.Count > 3 ? cascades[3].SplitFar : split2;
        var light1 = frame.PointLights.ElementAtOrDefault(0);
        var light2 = frame.PointLights.ElementAtOrDefault(1);
        var light3 = frame.PointLights.ElementAtOrDefault(2);
        var light4 = frame.PointLights.ElementAtOrDefault(3);
        var light5 = frame.PointLights.ElementAtOrDefault(4);
        var light6 = frame.PointLights.ElementAtOrDefault(5);
        var light7 = frame.PointLights.ElementAtOrDefault(6);
        var light8 = frame.PointLights.ElementAtOrDefault(7);
        var light9 = frame.PointLights.ElementAtOrDefault(8);
        var light10 = frame.PointLights.ElementAtOrDefault(9);
        var light11 = frame.PointLights.ElementAtOrDefault(10);
        var light12 = frame.PointLights.ElementAtOrDefault(11);
        var light13 = frame.PointLights.ElementAtOrDefault(12);
        var light14 = frame.PointLights.ElementAtOrDefault(13);
        var light15 = frame.PointLights.ElementAtOrDefault(14);
        var light16 = frame.PointLights.ElementAtOrDefault(15);
        var color1 = light1?.Color ?? frame.AdditionalLightColor;
        var position1 = light1?.Position ?? frame.AdditionalLightPosition;
        var parameters1 = light1?.Parameters ?? frame.AdditionalLightParameters;
        return new RekallAgeVulkanSceneGpuFrameUniform(
            ToGpuMatrix(frame.ViewProjection),
            frame.LightDirection.X,
            frame.LightDirection.Y,
            frame.LightDirection.Z,
            0,
            frame.LightColor.X,
            frame.LightColor.Y,
            frame.LightColor.Z,
            frame.LightColor.W,
            frame.LightPosition.X,
            frame.LightPosition.Y,
            frame.LightPosition.Z,
            frame.LightPosition.W,
            frame.CameraPosition.X,
            frame.CameraPosition.Y,
            frame.CameraPosition.Z,
            frame.CameraPosition.W,
            ToGpuMatrix(cascades.Count > 0 ? cascades[0].ViewProjection : Matrix4x4.Identity),
            ToGpuMatrix(cascades.Count > 1 ? cascades[1].ViewProjection : Matrix4x4.Identity),
            ToGpuMatrix(cascades.Count > 2 ? cascades[2].ViewProjection : Matrix4x4.Identity),
            ToGpuMatrix(cascades.Count > 3 ? cascades[3].ViewProjection : Matrix4x4.Identity),
            split0,
            split1,
            split2,
            split3,
            shadowPlan is { Enabled: true } ? cascades.Count : 0,
            shadowPlan?.Resolution ?? 1,
            shadowPlan?.DepthBias ?? 0,
            shadowPlan?.NormalBias ?? 0,
            shadowPlan?.FilterTapCount ?? 0,
            shadowPlan?.MaximumDistance ?? 0,
            shadowPlan is { Enabled: true } ? 1 : 0,
            0,
            shadowPlan?.CameraForward.X ?? 0,
            shadowPlan?.CameraForward.Y ?? 0,
            shadowPlan?.CameraForward.Z ?? 1,
            0,
            frame.AdditionalLightDirection.X,
            frame.AdditionalLightDirection.Y,
            frame.AdditionalLightDirection.Z,
            Math.Clamp(frame.PointLights.Count, 0, 16),
            color1.X, color1.Y, color1.Z, color1.W,
            position1.X, position1.Y, position1.Z, position1.W,
            parameters1.X, parameters1.Y, parameters1.Z, parameters1.W,
            light2?.Color.X ?? 0, light2?.Color.Y ?? 0, light2?.Color.Z ?? 0, light2?.Color.W ?? 0,
            light2?.Position.X ?? 0, light2?.Position.Y ?? 0, light2?.Position.Z ?? 0, light2?.Position.W ?? 0,
            light2?.Parameters.X ?? 0, light2?.Parameters.Y ?? 0, light2?.Parameters.Z ?? 0, light2?.Parameters.W ?? 0,
            light3?.Color.X ?? 0, light3?.Color.Y ?? 0, light3?.Color.Z ?? 0, light3?.Color.W ?? 0,
            light3?.Position.X ?? 0, light3?.Position.Y ?? 0, light3?.Position.Z ?? 0, light3?.Position.W ?? 0,
            light3?.Parameters.X ?? 0, light3?.Parameters.Y ?? 0, light3?.Parameters.Z ?? 0, light3?.Parameters.W ?? 0,
            light4?.Color.X ?? 0, light4?.Color.Y ?? 0, light4?.Color.Z ?? 0, light4?.Color.W ?? 0,
            light4?.Position.X ?? 0, light4?.Position.Y ?? 0, light4?.Position.Z ?? 0, light4?.Position.W ?? 0,
            light4?.Parameters.X ?? 0, light4?.Parameters.Y ?? 0, light4?.Parameters.Z ?? 0, light4?.Parameters.W ?? 0,
            light5?.Color.X ?? 0, light5?.Color.Y ?? 0, light5?.Color.Z ?? 0, light5?.Color.W ?? 0,
            light5?.Position.X ?? 0, light5?.Position.Y ?? 0, light5?.Position.Z ?? 0, light5?.Position.W ?? 0,
            light5?.Parameters.X ?? 0, light5?.Parameters.Y ?? 0, light5?.Parameters.Z ?? 0, light5?.Parameters.W ?? 0,
            light6?.Color.X ?? 0, light6?.Color.Y ?? 0, light6?.Color.Z ?? 0, light6?.Color.W ?? 0,
            light6?.Position.X ?? 0, light6?.Position.Y ?? 0, light6?.Position.Z ?? 0, light6?.Position.W ?? 0,
            light6?.Parameters.X ?? 0, light6?.Parameters.Y ?? 0, light6?.Parameters.Z ?? 0, light6?.Parameters.W ?? 0,
            light7?.Color.X ?? 0, light7?.Color.Y ?? 0, light7?.Color.Z ?? 0, light7?.Color.W ?? 0,
            light7?.Position.X ?? 0, light7?.Position.Y ?? 0, light7?.Position.Z ?? 0, light7?.Position.W ?? 0,
            light7?.Parameters.X ?? 0, light7?.Parameters.Y ?? 0, light7?.Parameters.Z ?? 0, light7?.Parameters.W ?? 0,
            light8?.Color.X ?? 0, light8?.Color.Y ?? 0, light8?.Color.Z ?? 0, light8?.Color.W ?? 0,
            light8?.Position.X ?? 0, light8?.Position.Y ?? 0, light8?.Position.Z ?? 0, light8?.Position.W ?? 0,
            light8?.Parameters.X ?? 0, light8?.Parameters.Y ?? 0, light8?.Parameters.Z ?? 0, light8?.Parameters.W ?? 0,
            light9?.Color.X ?? 0, light9?.Color.Y ?? 0, light9?.Color.Z ?? 0, light9?.Color.W ?? 0,
            light9?.Position.X ?? 0, light9?.Position.Y ?? 0, light9?.Position.Z ?? 0, light9?.Position.W ?? 0,
            light9?.Parameters.X ?? 0, light9?.Parameters.Y ?? 0, light9?.Parameters.Z ?? 0, light9?.Parameters.W ?? 0,
            light10?.Color.X ?? 0, light10?.Color.Y ?? 0, light10?.Color.Z ?? 0, light10?.Color.W ?? 0,
            light10?.Position.X ?? 0, light10?.Position.Y ?? 0, light10?.Position.Z ?? 0, light10?.Position.W ?? 0,
            light10?.Parameters.X ?? 0, light10?.Parameters.Y ?? 0, light10?.Parameters.Z ?? 0, light10?.Parameters.W ?? 0,
            light11?.Color.X ?? 0, light11?.Color.Y ?? 0, light11?.Color.Z ?? 0, light11?.Color.W ?? 0,
            light11?.Position.X ?? 0, light11?.Position.Y ?? 0, light11?.Position.Z ?? 0, light11?.Position.W ?? 0,
            light11?.Parameters.X ?? 0, light11?.Parameters.Y ?? 0, light11?.Parameters.Z ?? 0, light11?.Parameters.W ?? 0,
            light12?.Color.X ?? 0, light12?.Color.Y ?? 0, light12?.Color.Z ?? 0, light12?.Color.W ?? 0,
            light12?.Position.X ?? 0, light12?.Position.Y ?? 0, light12?.Position.Z ?? 0, light12?.Position.W ?? 0,
            light12?.Parameters.X ?? 0, light12?.Parameters.Y ?? 0, light12?.Parameters.Z ?? 0, light12?.Parameters.W ?? 0,
            light13?.Color.X ?? 0, light13?.Color.Y ?? 0, light13?.Color.Z ?? 0, light13?.Color.W ?? 0,
            light13?.Position.X ?? 0, light13?.Position.Y ?? 0, light13?.Position.Z ?? 0, light13?.Position.W ?? 0,
            light13?.Parameters.X ?? 0, light13?.Parameters.Y ?? 0, light13?.Parameters.Z ?? 0, light13?.Parameters.W ?? 0,
            light14?.Color.X ?? 0, light14?.Color.Y ?? 0, light14?.Color.Z ?? 0, light14?.Color.W ?? 0,
            light14?.Position.X ?? 0, light14?.Position.Y ?? 0, light14?.Position.Z ?? 0, light14?.Position.W ?? 0,
            light14?.Parameters.X ?? 0, light14?.Parameters.Y ?? 0, light14?.Parameters.Z ?? 0, light14?.Parameters.W ?? 0,
            light15?.Color.X ?? 0, light15?.Color.Y ?? 0, light15?.Color.Z ?? 0, light15?.Color.W ?? 0,
            light15?.Position.X ?? 0, light15?.Position.Y ?? 0, light15?.Position.Z ?? 0, light15?.Position.W ?? 0,
            light15?.Parameters.X ?? 0, light15?.Parameters.Y ?? 0, light15?.Parameters.Z ?? 0, light15?.Parameters.W ?? 0,
            light16?.Color.X ?? 0, light16?.Color.Y ?? 0, light16?.Color.Z ?? 0, light16?.Color.W ?? 0,
            light16?.Position.X ?? 0, light16?.Position.Y ?? 0, light16?.Position.Z ?? 0, light16?.Position.W ?? 0,
            light16?.Parameters.X ?? 0, light16?.Parameters.Y ?? 0, light16?.Parameters.Z ?? 0, light16?.Parameters.W ?? 0,
            frame.EnvironmentParameters.X,
            frame.EnvironmentParameters.Y,
            frame.EnvironmentParameters.Z,
            frame.EnvironmentParameters.W);
    }

    public static RekallAgeVulkanSceneGpuDrawPushConstants BuildDrawPushConstants(
        Matrix4x4 model,
        Vector4 materialFactors,
        Vector4 emissiveFactors,
        Vector4 atmosphereFactors0 = default,
        Vector4 atmosphereFactors1 = default,
        Vector4 atmosphereColor0 = default,
        Vector4 atmosphereColor1 = default,
        Vector4 atmosphereColor2 = default,
        Vector4 cloudFactors = default,
        Vector4 cloudColor = default,
        Vector4 cloudShadowFactors = default,
        Vector4 surfaceWaterFactors = default,
        bool castShadows = true,
        bool receiveShadows = true,
        string alphaMode = "opaque",
        float alphaCutoff = 0.5f)
    {
        return new RekallAgeVulkanSceneGpuDrawPushConstants(
            ToGpuMatrix(model),
            materialFactors.X,
            materialFactors.Y,
            materialFactors.Z,
            materialFactors.W,
            emissiveFactors.X,
            emissiveFactors.Y,
            emissiveFactors.Z,
            emissiveFactors.W,
            atmosphereFactors0.X,
            atmosphereFactors0.Y,
            atmosphereFactors0.Z,
            atmosphereFactors0.W,
            atmosphereFactors1.X,
            atmosphereFactors1.Y,
            atmosphereFactors1.Z,
            atmosphereFactors1.W,
            atmosphereColor0.X,
            atmosphereColor0.Y,
            atmosphereColor0.Z,
            atmosphereColor0.W,
            atmosphereColor1.X,
            atmosphereColor1.Y,
            atmosphereColor1.Z,
            atmosphereColor1.W,
            atmosphereColor2.X,
            atmosphereColor2.Y,
            atmosphereColor2.Z,
            atmosphereColor2.W,
            cloudFactors.X,
            cloudFactors.Y,
            cloudFactors.Z,
            cloudFactors.W,
            cloudColor.X,
            cloudColor.Y,
            cloudColor.Z,
            cloudColor.W,
            cloudShadowFactors.X,
            cloudShadowFactors.Y,
            cloudShadowFactors.Z,
            cloudShadowFactors.W,
            surfaceWaterFactors.X,
            surfaceWaterFactors.Y,
            surfaceWaterFactors.Z,
            surfaceWaterFactors.W,
            castShadows ? 1 : 0,
            receiveShadows ? 1 : 0,
            alphaMode.Equals("mask", StringComparison.OrdinalIgnoreCase) ? 1 : 0,
            Math.Clamp(alphaCutoff, 0, 1));
    }

    public static RekallAgeVulkanSceneGpuMatrix4x4 ToGpuMatrix(Matrix4x4 matrix)
    {
        return new RekallAgeVulkanSceneGpuMatrix4x4(
            matrix.M11,
            matrix.M12,
            matrix.M13,
            matrix.M14,
            matrix.M21,
            matrix.M22,
            matrix.M23,
            matrix.M24,
            matrix.M31,
            matrix.M32,
            matrix.M33,
            matrix.M34,
            matrix.M41,
            matrix.M42,
            matrix.M43,
            matrix.M44);
    }
}

[StructLayout(LayoutKind.Sequential)]
public readonly record struct RekallAgeVulkanSceneGpuMatrix4x4(
    float M11,
    float M12,
    float M13,
    float M14,
    float M21,
    float M22,
    float M23,
    float M24,
    float M31,
    float M32,
    float M33,
    float M34,
    float M41,
    float M42,
    float M43,
    float M44);

[StructLayout(LayoutKind.Sequential)]
public readonly record struct RekallAgeVulkanSceneGpuFrameUniform(
    RekallAgeVulkanSceneGpuMatrix4x4 ViewProjection,
    float LightX,
    float LightY,
    float LightZ,
    float LightPad,
    float LightR,
    float LightG,
    float LightB,
    float LightA,
    float LightPositionX,
    float LightPositionY,
    float LightPositionZ,
    float LightPositionW,
    float CameraPositionX,
    float CameraPositionY,
    float CameraPositionZ,
    float CameraPositionW,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection0,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection1,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection2,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection3,
    float ShadowSplit0,
    float ShadowSplit1,
    float ShadowSplit2,
    float ShadowSplit3,
    float ShadowCascadeCount,
    float ShadowResolution,
    float ShadowDepthBias,
    float ShadowNormalBias,
    float ShadowFilterTapCount,
    float ShadowMaximumDistance,
    float ShadowEnabled,
    float ShadowPad,
    float ShadowCameraForwardX,
    float ShadowCameraForwardY,
    float ShadowCameraForwardZ,
    float ShadowCameraForwardPad,
    float AdditionalLightDirectionX,
    float AdditionalLightDirectionY,
    float AdditionalLightDirectionZ,
    float AdditionalLightDirectionPad,
    float AdditionalLightR,
    float AdditionalLightG,
    float AdditionalLightB,
    float AdditionalLightA,
    float AdditionalLightPositionX,
    float AdditionalLightPositionY,
    float AdditionalLightPositionZ,
    float AdditionalLightPositionW,
    float AdditionalLightRange,
    float AdditionalLightPriority,
    float AdditionalLightParameterZ,
    float AdditionalLightParameterW,
    float AdditionalLight2R,
    float AdditionalLight2G,
    float AdditionalLight2B,
    float AdditionalLight2A,
    float AdditionalLight2PositionX,
    float AdditionalLight2PositionY,
    float AdditionalLight2PositionZ,
    float AdditionalLight2PositionW,
    float AdditionalLight2Range,
    float AdditionalLight2Priority,
    float AdditionalLight2ParameterZ,
    float AdditionalLight2ParameterW,
    float AdditionalLight3R,
    float AdditionalLight3G,
    float AdditionalLight3B,
    float AdditionalLight3A,
    float AdditionalLight3PositionX,
    float AdditionalLight3PositionY,
    float AdditionalLight3PositionZ,
    float AdditionalLight3PositionW,
    float AdditionalLight3Range,
    float AdditionalLight3Priority,
    float AdditionalLight3ParameterZ,
    float AdditionalLight3ParameterW,
    float AdditionalLight4R,
    float AdditionalLight4G,
    float AdditionalLight4B,
    float AdditionalLight4A,
    float AdditionalLight4PositionX,
    float AdditionalLight4PositionY,
    float AdditionalLight4PositionZ,
    float AdditionalLight4PositionW,
    float AdditionalLight4Range,
    float AdditionalLight4Priority,
    float AdditionalLight4ParameterZ,
    float AdditionalLight4ParameterW,
    float AdditionalLight5R,
    float AdditionalLight5G,
    float AdditionalLight5B,
    float AdditionalLight5A,
    float AdditionalLight5PositionX,
    float AdditionalLight5PositionY,
    float AdditionalLight5PositionZ,
    float AdditionalLight5PositionW,
    float AdditionalLight5Range,
    float AdditionalLight5Priority,
    float AdditionalLight5ParameterZ,
    float AdditionalLight5ParameterW,
    float AdditionalLight6R,
    float AdditionalLight6G,
    float AdditionalLight6B,
    float AdditionalLight6A,
    float AdditionalLight6PositionX,
    float AdditionalLight6PositionY,
    float AdditionalLight6PositionZ,
    float AdditionalLight6PositionW,
    float AdditionalLight6Range,
    float AdditionalLight6Priority,
    float AdditionalLight6ParameterZ,
    float AdditionalLight6ParameterW,
    float AdditionalLight7R,
    float AdditionalLight7G,
    float AdditionalLight7B,
    float AdditionalLight7A,
    float AdditionalLight7PositionX,
    float AdditionalLight7PositionY,
    float AdditionalLight7PositionZ,
    float AdditionalLight7PositionW,
    float AdditionalLight7Range,
    float AdditionalLight7Priority,
    float AdditionalLight7ParameterZ,
    float AdditionalLight7ParameterW,
    float AdditionalLight8R,
    float AdditionalLight8G,
    float AdditionalLight8B,
    float AdditionalLight8A,
    float AdditionalLight8PositionX,
    float AdditionalLight8PositionY,
    float AdditionalLight8PositionZ,
    float AdditionalLight8PositionW,
    float AdditionalLight8Range,
    float AdditionalLight8Priority,
    float AdditionalLight8ParameterZ,
    float AdditionalLight8ParameterW,
    float AdditionalLight9R,
    float AdditionalLight9G,
    float AdditionalLight9B,
    float AdditionalLight9A,
    float AdditionalLight9PositionX,
    float AdditionalLight9PositionY,
    float AdditionalLight9PositionZ,
    float AdditionalLight9PositionW,
    float AdditionalLight9Range,
    float AdditionalLight9Priority,
    float AdditionalLight9ParameterZ,
    float AdditionalLight9ParameterW,
    float AdditionalLight10R,
    float AdditionalLight10G,
    float AdditionalLight10B,
    float AdditionalLight10A,
    float AdditionalLight10PositionX,
    float AdditionalLight10PositionY,
    float AdditionalLight10PositionZ,
    float AdditionalLight10PositionW,
    float AdditionalLight10Range,
    float AdditionalLight10Priority,
    float AdditionalLight10ParameterZ,
    float AdditionalLight10ParameterW,
    float AdditionalLight11R,
    float AdditionalLight11G,
    float AdditionalLight11B,
    float AdditionalLight11A,
    float AdditionalLight11PositionX,
    float AdditionalLight11PositionY,
    float AdditionalLight11PositionZ,
    float AdditionalLight11PositionW,
    float AdditionalLight11Range,
    float AdditionalLight11Priority,
    float AdditionalLight11ParameterZ,
    float AdditionalLight11ParameterW,
    float AdditionalLight12R,
    float AdditionalLight12G,
    float AdditionalLight12B,
    float AdditionalLight12A,
    float AdditionalLight12PositionX,
    float AdditionalLight12PositionY,
    float AdditionalLight12PositionZ,
    float AdditionalLight12PositionW,
    float AdditionalLight12Range,
    float AdditionalLight12Priority,
    float AdditionalLight12ParameterZ,
    float AdditionalLight12ParameterW,
    float AdditionalLight13R,
    float AdditionalLight13G,
    float AdditionalLight13B,
    float AdditionalLight13A,
    float AdditionalLight13PositionX,
    float AdditionalLight13PositionY,
    float AdditionalLight13PositionZ,
    float AdditionalLight13PositionW,
    float AdditionalLight13Range,
    float AdditionalLight13Priority,
    float AdditionalLight13ParameterZ,
    float AdditionalLight13ParameterW,
    float AdditionalLight14R,
    float AdditionalLight14G,
    float AdditionalLight14B,
    float AdditionalLight14A,
    float AdditionalLight14PositionX,
    float AdditionalLight14PositionY,
    float AdditionalLight14PositionZ,
    float AdditionalLight14PositionW,
    float AdditionalLight14Range,
    float AdditionalLight14Priority,
    float AdditionalLight14ParameterZ,
    float AdditionalLight14ParameterW,
    float AdditionalLight15R,
    float AdditionalLight15G,
    float AdditionalLight15B,
    float AdditionalLight15A,
    float AdditionalLight15PositionX,
    float AdditionalLight15PositionY,
    float AdditionalLight15PositionZ,
    float AdditionalLight15PositionW,
    float AdditionalLight15Range,
    float AdditionalLight15Priority,
    float AdditionalLight15ParameterZ,
    float AdditionalLight15ParameterW,
    float AdditionalLight16R,
    float AdditionalLight16G,
    float AdditionalLight16B,
    float AdditionalLight16A,
    float AdditionalLight16PositionX,
    float AdditionalLight16PositionY,
    float AdditionalLight16PositionZ,
    float AdditionalLight16PositionW,
    float AdditionalLight16Range,
    float AdditionalLight16Priority,
    float AdditionalLight16ParameterZ,
    float AdditionalLight16ParameterW,
    float EnvironmentAmbientEnergy,
    float EnvironmentExposure,
    float EnvironmentWhitePoint,
    float EnvironmentToneMapper);

[StructLayout(LayoutKind.Sequential)]
public readonly record struct RekallAgeVulkanSceneGpuDrawPushConstants(
    RekallAgeVulkanSceneGpuMatrix4x4 Model,
    float MetallicFactor,
    float RoughnessFactor,
    float NormalScale,
    float OcclusionStrength,
    float EmissiveR,
    float EmissiveG,
    float EmissiveB,
    float EmissiveStrength,
    float AtmospherePlanetRadius,
    float AtmosphereRadius,
    float AtmosphereDensity,
    float AtmosphereDensityFalloff,
    float AtmosphereRayleighScattering,
    float AtmosphereMieScattering,
    float AtmosphereMieAnisotropy,
    float AtmosphereSunIntensity,
    float AtmosphereRayleighR,
    float AtmosphereRayleighG,
    float AtmosphereRayleighB,
    float AtmosphereRayleighA,
    float AtmosphereMieR,
    float AtmosphereMieG,
    float AtmosphereMieB,
    float AtmosphereAerialPerspectiveStrength,
    float AtmosphereOzoneR,
    float AtmosphereOzoneG,
    float AtmosphereOzoneB,
    float AtmosphereOzoneAbsorption,
    float CloudAlphaFromTextureOnly,
    float CloudCoverage,
    float CloudLambertianStrength,
    float CloudAmbientStrength,
    float CloudColorR,
    float CloudColorG,
    float CloudColorB,
    float CloudColorA,
    float CloudShadowEnabled,
    float CloudShadowRadius,
    float CloudShadowStrength,
    float CloudShadowPad,
    float SurfaceWaterEnabled,
    float SurfaceWaterCoverage,
    float SurfaceWaterSpecularStrength,
    float SurfaceWaterRoughness,
    float CastShadows,
    float ReceiveShadows,
    float AlphaMask,
    float AlphaCutoff);
