using System.Numerics;
using System.Runtime.InteropServices;

namespace Rekall.Age.Rendering;

public static class RekallAgeVulkanSceneUniformUploadBuilder
{
    public static RekallAgeVulkanSceneGpuFrameUniform BuildFrameUniform(
        RekallAgeVulkanSceneFrameUniform frame,
        RekallAgeVulkanShadowPlan? shadowPlan = null)
    {
        var cascades = shadowPlan?.Cascades ?? [];
        var split0 = cascades.Count > 0 ? cascades[0].SplitFar : 0;
        var split1 = cascades.Count > 1 ? cascades[1].SplitFar : split0;
        var split2 = cascades.Count > 2 ? cascades[2].SplitFar : split1;
        var split3 = cascades.Count > 3 ? cascades[3].SplitFar : split2;
        return new RekallAgeVulkanSceneGpuFrameUniform(
            ToGpuMatrix(frame.ViewProjection),
            frame.LightDirection.X,
            frame.LightDirection.Y,
            frame.LightDirection.Z,
            0,
            frame.LightColor.X,
            frame.LightColor.Y,
            frame.LightColor.Z,
            frame.LightColor.W,
            frame.LightPosition.X,
            frame.LightPosition.Y,
            frame.LightPosition.Z,
            frame.LightPosition.W,
            frame.CameraPosition.X,
            frame.CameraPosition.Y,
            frame.CameraPosition.Z,
            frame.CameraPosition.W,
            ToGpuMatrix(cascades.Count > 0 ? cascades[0].ViewProjection : Matrix4x4.Identity),
            ToGpuMatrix(cascades.Count > 1 ? cascades[1].ViewProjection : Matrix4x4.Identity),
            ToGpuMatrix(cascades.Count > 2 ? cascades[2].ViewProjection : Matrix4x4.Identity),
            ToGpuMatrix(cascades.Count > 3 ? cascades[3].ViewProjection : Matrix4x4.Identity),
            split0,
            split1,
            split2,
            split3,
            shadowPlan is { Enabled: true } ? cascades.Count : 0,
            shadowPlan?.Resolution ?? 1,
            shadowPlan?.DepthBias ?? 0,
            shadowPlan?.NormalBias ?? 0,
            shadowPlan?.FilterTapCount ?? 0,
            shadowPlan?.MaximumDistance ?? 0,
            shadowPlan is { Enabled: true } ? 1 : 0,
            0,
            shadowPlan?.CameraForward.X ?? 0,
            shadowPlan?.CameraForward.Y ?? 0,
            shadowPlan?.CameraForward.Z ?? 1,
            0,
            frame.AdditionalLightDirection.X,
            frame.AdditionalLightDirection.Y,
            frame.AdditionalLightDirection.Z,
            0,
            frame.AdditionalLightColor.X,
            frame.AdditionalLightColor.Y,
            frame.AdditionalLightColor.Z,
            frame.AdditionalLightColor.W,
            frame.AdditionalLightPosition.X,
            frame.AdditionalLightPosition.Y,
            frame.AdditionalLightPosition.Z,
            frame.AdditionalLightPosition.W);
    }

    public static RekallAgeVulkanSceneGpuDrawPushConstants BuildDrawPushConstants(
        Matrix4x4 model,
        Vector4 materialFactors,
        Vector4 emissiveFactors,
        Vector4 atmosphereFactors0 = default,
        Vector4 atmosphereFactors1 = default,
        Vector4 atmosphereColor0 = default,
        Vector4 atmosphereColor1 = default,
        Vector4 atmosphereColor2 = default,
        Vector4 cloudFactors = default,
        Vector4 cloudColor = default,
        Vector4 cloudShadowFactors = default,
        Vector4 surfaceWaterFactors = default,
        bool castShadows = true,
        bool receiveShadows = true,
        string alphaMode = "opaque",
        float alphaCutoff = 0.5f)
    {
        return new RekallAgeVulkanSceneGpuDrawPushConstants(
            ToGpuMatrix(model),
            materialFactors.X,
            materialFactors.Y,
            materialFactors.Z,
            materialFactors.W,
            emissiveFactors.X,
            emissiveFactors.Y,
            emissiveFactors.Z,
            emissiveFactors.W,
            atmosphereFactors0.X,
            atmosphereFactors0.Y,
            atmosphereFactors0.Z,
            atmosphereFactors0.W,
            atmosphereFactors1.X,
            atmosphereFactors1.Y,
            atmosphereFactors1.Z,
            atmosphereFactors1.W,
            atmosphereColor0.X,
            atmosphereColor0.Y,
            atmosphereColor0.Z,
            atmosphereColor0.W,
            atmosphereColor1.X,
            atmosphereColor1.Y,
            atmosphereColor1.Z,
            atmosphereColor1.W,
            atmosphereColor2.X,
            atmosphereColor2.Y,
            atmosphereColor2.Z,
            atmosphereColor2.W,
            cloudFactors.X,
            cloudFactors.Y,
            cloudFactors.Z,
            cloudFactors.W,
            cloudColor.X,
            cloudColor.Y,
            cloudColor.Z,
            cloudColor.W,
            cloudShadowFactors.X,
            cloudShadowFactors.Y,
            cloudShadowFactors.Z,
            cloudShadowFactors.W,
            surfaceWaterFactors.X,
            surfaceWaterFactors.Y,
            surfaceWaterFactors.Z,
            surfaceWaterFactors.W,
            castShadows ? 1 : 0,
            receiveShadows ? 1 : 0,
            alphaMode.Equals("mask", StringComparison.OrdinalIgnoreCase) ? 1 : 0,
            Math.Clamp(alphaCutoff, 0, 1));
    }

    public static RekallAgeVulkanSceneGpuMatrix4x4 ToGpuMatrix(Matrix4x4 matrix)
    {
        return new RekallAgeVulkanSceneGpuMatrix4x4(
            matrix.M11,
            matrix.M12,
            matrix.M13,
            matrix.M14,
            matrix.M21,
            matrix.M22,
            matrix.M23,
            matrix.M24,
            matrix.M31,
            matrix.M32,
            matrix.M33,
            matrix.M34,
            matrix.M41,
            matrix.M42,
            matrix.M43,
            matrix.M44);
    }
}

[StructLayout(LayoutKind.Sequential)]
public readonly record struct RekallAgeVulkanSceneGpuMatrix4x4(
    float M11,
    float M12,
    float M13,
    float M14,
    float M21,
    float M22,
    float M23,
    float M24,
    float M31,
    float M32,
    float M33,
    float M34,
    float M41,
    float M42,
    float M43,
    float M44);

[StructLayout(LayoutKind.Sequential)]
public readonly record struct RekallAgeVulkanSceneGpuFrameUniform(
    RekallAgeVulkanSceneGpuMatrix4x4 ViewProjection,
    float LightX,
    float LightY,
    float LightZ,
    float LightPad,
    float LightR,
    float LightG,
    float LightB,
    float LightA,
    float LightPositionX,
    float LightPositionY,
    float LightPositionZ,
    float LightPositionW,
    float CameraPositionX,
    float CameraPositionY,
    float CameraPositionZ,
    float CameraPositionW,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection0,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection1,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection2,
    RekallAgeVulkanSceneGpuMatrix4x4 ShadowViewProjection3,
    float ShadowSplit0,
    float ShadowSplit1,
    float ShadowSplit2,
    float ShadowSplit3,
    float ShadowCascadeCount,
    float ShadowResolution,
    float ShadowDepthBias,
    float ShadowNormalBias,
    float ShadowFilterTapCount,
    float ShadowMaximumDistance,
    float ShadowEnabled,
    float ShadowPad,
    float ShadowCameraForwardX,
    float ShadowCameraForwardY,
    float ShadowCameraForwardZ,
    float ShadowCameraForwardPad,
    float AdditionalLightDirectionX,
    float AdditionalLightDirectionY,
    float AdditionalLightDirectionZ,
    float AdditionalLightDirectionPad,
    float AdditionalLightR,
    float AdditionalLightG,
    float AdditionalLightB,
    float AdditionalLightA,
    float AdditionalLightPositionX,
    float AdditionalLightPositionY,
    float AdditionalLightPositionZ,
    float AdditionalLightPositionW);

[StructLayout(LayoutKind.Sequential)]
public readonly record struct RekallAgeVulkanSceneGpuDrawPushConstants(
    RekallAgeVulkanSceneGpuMatrix4x4 Model,
    float MetallicFactor,
    float RoughnessFactor,
    float NormalScale,
    float OcclusionStrength,
    float EmissiveR,
    float EmissiveG,
    float EmissiveB,
    float EmissiveStrength,
    float AtmospherePlanetRadius,
    float AtmosphereRadius,
    float AtmosphereDensity,
    float AtmosphereDensityFalloff,
    float AtmosphereRayleighScattering,
    float AtmosphereMieScattering,
    float AtmosphereMieAnisotropy,
    float AtmosphereSunIntensity,
    float AtmosphereRayleighR,
    float AtmosphereRayleighG,
    float AtmosphereRayleighB,
    float AtmosphereRayleighA,
    float AtmosphereMieR,
    float AtmosphereMieG,
    float AtmosphereMieB,
    float AtmosphereAerialPerspectiveStrength,
    float AtmosphereOzoneR,
    float AtmosphereOzoneG,
    float AtmosphereOzoneB,
    float AtmosphereOzoneAbsorption,
    float CloudAlphaFromTextureOnly,
    float CloudCoverage,
    float CloudLambertianStrength,
    float CloudAmbientStrength,
    float CloudColorR,
    float CloudColorG,
    float CloudColorB,
    float CloudColorA,
    float CloudShadowEnabled,
    float CloudShadowRadius,
    float CloudShadowStrength,
    float CloudShadowPad,
    float SurfaceWaterEnabled,
    float SurfaceWaterCoverage,
    float SurfaceWaterSpecularStrength,
    float SurfaceWaterRoughness,
    float CastShadows,
    float ReceiveShadows,
    float AlphaMask,
    float AlphaCutoff);
