using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using Rekall.Age.Assets;
using Rekall.Age.Core.Commands;

namespace Rekall.Age.AssetPipeline.Commands;

public sealed record GenerateTextureRequest(
    string ProjectRoot,
    string Prompt,
    string? DisplayName = null,
    string TextureRole = "baseColor",
    string Size = "1024x1024",
    string Quality = "auto",
    bool Seamless = false,
    string? Provider = null,
    string? Model = null,
    string? ApiKey = null,
    bool UseEnvironmentApiKey = true);

public sealed record GenerateTextureResult(
    string Provider,
    string Model,
    string TextureRole,
    RekallAgeAssetDocument? Asset,
    string? StagingPath,
    IReadOnlyList<string> NextActions);

public sealed record RekallAgeTextureGenerationOptions(
    string Prompt,
    string Model,
    string Size,
    string Quality,
    bool Seamless);

public interface IRekallAgeTextureGenerationClient
{
    ValueTask<byte[]> GenerateAsync(
        RekallAgeTextureGenerationOptions options,
        string apiKey,
        CancellationToken cancellationToken);
}

public sealed class GenerateTextureCommand
    : IRekallAgeCommand<GenerateTextureRequest, GenerateTextureResult>
{
    public const string DefaultProvider = "openai";
    public const string DefaultModel = "gpt-image-2";
    private readonly IRekallAgeTextureGenerationClient _client;
    private readonly RekallAgeAssetCatalogStore _assetStore = new();
    private readonly RekallAgeAssetPipelineStore _pipelineStore = new();

    public GenerateTextureCommand() : this(new RekallAgeOpenAiTextureGenerationClient()) { }

    public GenerateTextureCommand(IRekallAgeTextureGenerationClient client) => _client = client;

    public string Name => "rekall.asset.generate_texture";

    public RekallAgeCommandSchema Schema => new(
        Name,
        "Generates a texture through a selectable image provider and imports it into the generic Rekall AGE asset catalog with provenance.",
        typeof(GenerateTextureRequest).FullName!,
        typeof(GenerateTextureResult).FullName!);

    public async ValueTask<RekallAgeCommandResult<GenerateTextureResult>> ExecuteAsync(
        GenerateTextureRequest request,
        RekallAgeCommandContext context)
    {
        var provider = TrimToNull(request.Provider)?.ToLowerInvariant() ?? DefaultProvider;
        var model = TrimToNull(request.Model) ?? DefaultModel;
        if (string.IsNullOrWhiteSpace(request.Prompt))
            return Failure("TEXTURE_PROMPT_REQUIRED", "Texture generation requires a non-empty prompt.", provider, model, request.TextureRole);
        if (provider != DefaultProvider)
            return Failure("TEXTURE_PROVIDER_UNSUPPORTED", $"Texture provider '{provider}' is not installed. Supported providers: openai.", provider, model, request.TextureRole);

        var apiKey = TrimToNull(request.ApiKey) ?? (request.UseEnvironmentApiKey
            ? TrimToNull(Environment.GetEnvironmentVariable("OPENAI_API_KEY"))
            : null);
        if (apiKey is null)
            return Failure("TEXTURE_API_KEY_MISSING", "Set OPENAI_API_KEY or pass an API key in the request before generating a texture.", provider, model, request.TextureRole);

        var options = new RekallAgeTextureGenerationOptions(
            request.Prompt.Trim(), model, request.Size.Trim(), request.Quality.Trim(), request.Seamless);
        var bytes = await _client.GenerateAsync(options, apiKey, context.CancellationToken);
        if (bytes.Length == 0)
            return Failure("TEXTURE_IMAGE_MISSING", "The texture provider returned no image bytes.", provider, model, request.TextureRole);

        var stagingDirectory = Path.Combine(Path.GetFullPath(request.ProjectRoot), "Assets", ".staging", "texture-generation", Guid.NewGuid().ToString("N"));
        var stagingPath = Path.Combine(stagingDirectory, "generated.png");
        Directory.CreateDirectory(stagingDirectory);
        try
        {
            await File.WriteAllBytesAsync(stagingPath, bytes, context.CancellationToken);
            var imported = await RekallAgeAssetImporter.ImportAsync(
                request.ProjectRoot, stagingPath, "texture", request.DisplayName, context.CancellationToken);
            var hash = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
            var asset = imported with
            {
                SourcePath = $"openai://images/generations/{model}",
                Provenance = new RekallAgeAssetProvenance(
                    $"openai://images/generations/{model}",
                    $"openai://images/generations/{model}",
                    DateTimeOffset.UtcNow,
                    "image/png",
                    bytes.LongLength,
                    hash,
                    $"Generated by OpenAI {model}; prompt: {request.Prompt.Trim()}",
                    null,
                    null)
            };
            await _assetStore.AddOrReplaceAsync(request.ProjectRoot, asset, context.CancellationToken);
            var pipeline = await _pipelineStore.LoadAsync(request.ProjectRoot, context.CancellationToken);
            await _pipelineStore.SaveAsync(
                request.ProjectRoot,
                pipeline.AddImport(asset, asset.SourcePath, "texture"),
                context.CancellationToken);

            context.Transaction.RecordChangedResource(asset.ImportedPath);
            context.Transaction.RecordChangedResource(_assetStore.GetCatalogPath(request.ProjectRoot));
            context.Transaction.RecordChangedResource(_pipelineStore.GetPath(request.ProjectRoot));
            return RekallAgeCommandResult<GenerateTextureResult>.Success(
                new(provider, model, request.TextureRole, asset, stagingPath,
                    ["Use rekall.asset.list to inspect the imported texture.", "Assign the asset id to a material or renderer texture property matching textureRole."]),
                $"Generated and imported texture asset '{asset.Id}' with OpenAI {model}.");
        }
        finally
        {
            if (Directory.Exists(stagingDirectory)) Directory.Delete(stagingDirectory, recursive: true);
        }
    }

    private static string? TrimToNull(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private static RekallAgeCommandResult<GenerateTextureResult> Failure(string code, string message, string provider, string model, string role) =>
        RekallAgeCommandResult<GenerateTextureResult>.Failure(
            new(provider, model, role, null, null, ["Correct the request or provider credentials, then retry texture generation."]),
            message,
            [new RekallAgeCommandError(code, message, provider)]);
}

public sealed class RekallAgeOpenAiTextureGenerationClient : IRekallAgeTextureGenerationClient
{
    private static readonly Uri Endpoint = new("https://api.openai.com/v1/images/generations");
    private readonly HttpClient _httpClient;

    public RekallAgeOpenAiTextureGenerationClient() : this(new HttpClient()) { }
    public RekallAgeOpenAiTextureGenerationClient(HttpClient httpClient) => _httpClient = httpClient;

    public async ValueTask<byte[]> GenerateAsync(RekallAgeTextureGenerationOptions options, string apiKey, CancellationToken cancellationToken)
    {
        var prompt = options.Seamless
            ? options.Prompt + " Create a seamless, tileable texture with matching opposite edges."
            : options.Prompt;
        var payload = new JsonObject
        {
            ["model"] = options.Model,
            ["prompt"] = prompt,
            ["size"] = options.Size,
            ["quality"] = options.Quality,
            ["n"] = 1,
            ["output_format"] = "png"
        };
        using var request = new HttpRequestMessage(HttpMethod.Post, Endpoint)
        {
            Content = new StringContent(payload.ToJsonString(), Encoding.UTF8, "application/json")
        };
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
        using var response = await _httpClient.SendAsync(request, cancellationToken);
        var body = await response.Content.ReadAsStringAsync(cancellationToken);
        response.EnsureSuccessStatusCode();
        var encoded = JsonNode.Parse(body)?["data"]?[0]?["b64_json"]?.GetValue<string>()
            ?? throw new InvalidDataException("OpenAI image response did not include data[0].b64_json.");
        return Convert.FromBase64String(encoded);
    }
}
